// const shell = require("shelljs");
// // shell.cd("D:/works/ka-web");
// shell.exec("cd D:/works/ka-web");
// shell.exec("git add .");
// shell.exec("git commit -m 测试");
// var a = 1;
// var a = (b = 1);
// b = 2;
// console.log(a);
// console.log(b);
// let arr = [1, 2, 3];
// let brr = [4, 5, 6];
// // console.log(arr.valueOf());
// // console.log(arr.sort((a, b) => a - b));
// arr.splice(1, 0, ...brr);
// console.log(arr);
// console.log(+0 === -0);
let map = new Map();
map.set(-0, "负零");
map.set(+0, "正零");
console.log(map);
let set = new Set([-0, +0]);
console.log(set);
